### ISSUE TITLE
Highlight selected cluster in a different color. 

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#36]
Seems like selected cluster should be highlighted a different color so you can tell which cluster info you are viewing. 

Charcoal, perhaps?

**Comment by wrenaria** [comment]
- [x] The transparent part of the circle should also change color when selected.

- [x] The cluster still shows as selected when you click a dot on the map, but it shouldn't. For example, in this screenshot I first clicked the cluster of 15, and then clicked on Steven Spurrier:

![Screen Shot 2020-03-10 at 3 10 57 PM](https://user-images.githubusercontent.com/17831969/76364051-88c50b80-62e1-11ea-8623-96ca6379717a.png)

The cluster should return to being blue when no longer actively selected.

**Comment by wrenaria** [comment]
This has ceased working for me altogether. It flashed black for a fraction of a second on click but stay blue unless I click it a second time (which no one will do).

**Comment by ldragoon** [comment]
Issue Notes:

1. Due to the nature of the clustering algorithm, a cluster only exists at a certain lat/lng & zoom.  This means the clusters change based on the zoom.  The 'selectCluster' in the app-leaflet-map looks at the current latlng and zoom and tries to find the marker that is most similar.

2. Justin's suggested fix: render only the cluster whose data is shown on the left info box as selected. Don't render a cluster as selected just because the lat/lng matches in selectCluster(). Check the provided zoom value as well. If the map doesn't match the current zoom, don't render as selected.

3. Will need to have @wrenaria review.

**Comment by wrenaria** [comment]
This sounds correct. If a user zooms in while a cluster is selected and the cluster breaks apart into smaller ones, it should be deselected and the info panel reverts to the blue intro panel as the cluster ceases to exist in that view (true for zoom out/cluster merges as well).

**Comment by wrenaria** [comment]
Two things are not working correctly:

1. When you zoom and cluster still exists (doesn't break apart or merge into another), it no longer shows as selected on the map. This is not good, as the cluster has not changed and thus should still show as selected.

2. When you zoom and the selected cluster DOES break apart (zoom in) or merge with another (zoom out), it currently still shows the panel for the cluster that no longer exists. This should not be the case. When large a cluster breaks into smaller clusters or dots or vice versa, the info panel should revert to the default blue panel, because technically nothing is selected. 

To be clear, this is only true of clusters. If a user has an individual subject selected, it should remain selected no matter the zoom level until they select something else.
