### ISSUE TITLE
App Offline Alert - Total Worst Case Scenario

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/intertwine#44]
Roughed out the appearance and functionality:

![image](https://user-images.githubusercontent.com/7807437/77090349-3e6c1a80-69c4-11ea-96f8-c93b0003e105.png)

1. Buttons on page are disabled
2. Attempt to navigate away from home page re-routes user to home page
3. Banner explaining the outage

**Comment by wrenaria** [comment]
@ldragoon If the stories still work (text and image), then the banner doesn't need to be on the front page, just on the maps. Please hold off on this until we chat about it and I provide a mock-up. I was too busy helping Jessica yesterday to get to this task. In the future, when you need UI elements like this, please create an issue and assign to me and I'll get to it when I can.

**Comment by wrenaria** [comment]
Alright, let's keep it simple. Since nothing will be available to view, I'd like to maintain the base look of the site (site header, blue link to UCD Library, background) and then have an error message paired with the "error" iron icon.

If it's easier to not have the background image, then I can also live with the background just being the color smoke/#F3F2F0 instead. 

![intertWINE-error](https://user-images.githubusercontent.com/17831969/77098335-6f9e1800-69cf-11ea-9847-3127757b1a71.png)

Specs:

![intertWINE-error-specs](https://user-images.githubusercontent.com/17831969/77099172-bf311380-69d0-11ea-860b-2ce88ad05855.png)

**Comment by ldragoon** [comment]
@wrenaria 

![image](https://user-images.githubusercontent.com/7807437/77102827-b2afb980-69d6-11ea-99f1-04561dd131ab.png)

**Comment by wrenaria** [comment]
👍👍
