### ISSUE TITLE
Intertwine App Front End UI Corrections

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/intertwine#62]
**Home Page** 

- [x] Card should max out at 2 per column. 

- [x] Responsive behavior - make sure space between 2 home page cards is consistent no matter what size.

**Stories**

- [x] Text box should always hug the middle of the screen in text/image

- [x] Float text in vertical center of textboxes

- [x] Make sure spacing between tags is consistent.

**Comment by wrenaria** [comment]
For the "Text box should always hug the middle of the screen in text/image" problem, its hard for me to know if this working because right now, text boxes are not currently maxing out in width, they are just stretching indefinitely. 

**Text areas should never stretch to be wider than 750px wide to maintain readability.** 

Which means it should never look like this:

![Screen Shot 2020-09-29 at 3 53 12 PM](https://user-images.githubusercontent.com/17831969/94624878-4ad30900-026c-11eb-8f0d-5b9871648a95.png)

The pink overlaid on the image below shows where the text width and placement should be if text width limits were in place:

![Artboard – 1](https://user-images.githubusercontent.com/17831969/94624898-57eff800-026c-11eb-98de-45c9431fd65e.png)
